export default {
    name:'comment',
    title:'Comment',
    type:'document',
    fields:[
        {
            name:'image',
            title:'Image',
            type:'string'
        },
        {
            name:'userName',
            title:'userName',
            type:'string'
        },
        {
            name:'postedBy',
            title:'PostedBy',
            type:'postedBy'
        },
        {
            name:'comment',
            title:'Comment',
            type:'string'
        }
    ]
}